# Stage 1: Build stage
FROM eclipse-temurin:21-jdk-alpine AS builder
WORKDIR /app
RUN apk add --no-cache bash
COPY build.gradle.kts gradlew settings.gradle.kts ./
COPY gradle ./gradle
RUN ./gradlew dependencies --no-daemon
COPY src ./src
RUN ./gradlew bootJar -x test --no-daemon

# Stage 2: Runtime stage
FROM eclipse-temurin:21-jre-alpine
WORKDIR /opt
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
COPY --from=builder /app/build/libs/backend-0.0.1-SNAPSHOT.jar /opt/app.jar
RUN chown appuser:appgroup /opt/app.jar
USER appuser
# Adjust memory settings as needed (min heap size, max heap size)
ENV JAVA_OPTS="-Xms256m -Xmx512m" 

EXPOSE 8080
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /opt/app.jar"]